### ISSUE TITLE
严格模式好像有点问题

### ISSUE THREAD

**Issue by jeffreymor** [XIU2/Shell#1]
我自己按源项目作者说的加-s -e http://music.163.com 是可以正常运行的，你可以看看这一块是不是有问题

**Comment by XIU2** [comment]
我测试能用啊，我写完脚本时就测试了，不需要加 -e，刚才我又安装测试了以下也正常，只有 -s 。
测试环境：UWP客户端，周杰伦的无版权音乐。

**Comment by jeffreymor** [comment]
我一开始也认为是自己问题，本来用的GCP的服务器，后来又开了台腾讯云的服务器，也是这样的问题，我也不清楚了

**Comment by XIU2** [comment]
我测试是加不加 -e 都能正常用，测试服务器是国外的。

**Comment by jeffreymor** [comment]
隔壁几个issue都有回复说开严格模式后要加-e xxx，你可以看看，我的现象和他们一样的都是能正常加载歌曲信息但播放加载的时候会失败，我这边测试开了严格模式不加-e的确是有问题。。

**Comment by XIU2** [comment]
应该是你使用的是 腾讯云 谷歌云 这种内外网分开的服务器的原因，我用的是VPS测试的。
那就加上吧，现在有事没空，下午或晚上有空了加上。

**Comment by XIU2** [comment]
我更新了，但是 Github 有CDN缓存，你等一会再用脚本内的 0. 更新脚本 功能更新脚本再试试。

**Comment by jeffreymor** [comment]
1.0.1开启严格模式提示参数有问题，我看了下提交记录你-e 参数后面多了个大括号，我删了之后就正常了😄

**Comment by XIU2** [comment]
已修复，请更新脚本（等待Github更新缓存）。
中午的时候空闲时间更新没来得及测试就上传了，我的锅...
