### ISSUE TITLE
[BUG/unblock163.sh] - 开始下载/安装... 后退出

### ISSUE THREAD

**Issue by albatr0n** [XIU2/Shell#10]
### 脚本名称
 unblock163.sh

### BUG描述
执行安装后，在【开始下载/安装……】步骤后自动退出到命令行

### 重现步骤
BUG重现完整步骤:
1. 下载、赋权并执行脚本
2. 输入各选项后开始安装过程
3. 显示【开始下载/安装……】自动退出

### 预期行为
脚本正常安装或重新执行后显示已安装

### 截图/报错内容
![截屏2019-12-0213 27 37](https://user-images.githubusercontent.com/12709679/69923267-649aa700-1508-11ea-87cd-dd4e4d40448f.png)

### 设备信息
如果你出现问题的是**服务器**，那么请提供相关详细信息，包括但不限于：
 - 阿里云
 - Ubuntu 18.04.3
 - x64

**Comment by XIU2** [comment]
[#1b35132](https://github.com/XIU2/SHELL/commit/1b35132e9bc9add3f0e8689ab0f28d7d5a5ea1c8)

****

## 更新内容：
### 2019年12月02日，版本 v1.0.5
 - **1. 修复** 安装时异常退出的问题。

****

## 更新方法：
请选择 `[0. 更新脚本]` 更新脚本，或重新下载脚本：
```
wget -N --no-check-certificate https://raw.githubusercontent.com/XIU2/SHELL/master/unblock163.sh && chmod +x unblock163.sh && bash unblock163.sh
```

****

如果测试没问题了，请手动关闭该问题。
