### ISSUE TITLE
外网服务器似乎无法使用~

### ISSUE THREAD

**Issue by xiexinxinclimb** [XIU2/Shell#11]
- 服务器的服务商：谷歌云
 - 系统名称即具体版本：Debian 9
能够检查到代理连接到服务器，但是需要解锁的音乐无法成功播放，之前在阿里云（国内）是可以的

**Comment by XIU2** [comment]
首先，目前最新版本的各个平台网易云音乐客户端都不再自动降级 HTTP 了，所以要么自签证书用 HTTPS，要么使用旧版本网易云音乐客户端。

其次，谷歌云需要去后台开放外部防火墙，开放后请去在线 TCPing 网站测试一下端口是否通顺。
