### ISSUE TITLE
pac模式只有windows客户端和ipad客户端可用

### ISSUE THREAD

**Issue by zhouchangyi** [XIU2/Shell#12]
您好，我用的是天翼云服务器，由于没有备案，没有开放80端口。于是用的别的端口
我通过windows网易云音乐客户端设置的http代理可用。
ios方面，ipad在wlan试用pac可以试用ipad网易云客户端，但是iphone客户端不可以，会提示网络不给力。然后安卓客户端在wlan里添加了pac歌曲还是灰色的，然后在原项目里看到安卓需要屏蔽一个ip，但是屏蔽了其实还是灰色的，一看帖子是两年前的了。不知道怎么解决呢。

如果使用host模式，是不是这些客户端就都可以了呢，期待您的回复；）

**Comment by XIU2** [comment]
emmmm 你这个问题应该去主程序项目询问 [UnblockNeteaseMusic](https://github.com/nondanee/UnblockNeteaseMusic) 。。。

我这个项目只是一个 Linux 的一键脚本，只负责脚本使用相关的问题，你问的问题不在我的项目范畴内，而且我并没有 IOS 设备、同时有一段时间没使用这个软件了。

另外，前段时间网易云音乐就各平台客户端统一更新了，包括万年不更新的 Win10 UWP 版本，应该是取消 HTTPS 无法连接后降级 HTTP 的行为了，这样普通方式使用就没办法了，只有自签证书，然后设备导入证书后才行了。

**Comment by zhouchangyi** [comment]
好的，我再找找其他办法，非常感谢您的回复，祝您生活愉快！




------------------&nbsp;Original&nbsp;------------------
