### ISSUE TITLE
[BUG] - IOS13不能连接到网络

### ISSUE THREAD

**Issue by zhangheng2022** [XIU2/Shell#13]
### 脚本名称
xxx.sh

### BUG描述
IOS13不能连接到网络，加载不了歌曲目录，PC客户端没有问题，已经添加了https,域名，并且手机端信任了证书，还是无法加载播放，PC端可以使用HTTPS域名连接

### 重现步骤
BUG重现完整步骤:
1. 运行...
2. 输入...
3. ...
4. 显示错误

### 预期行为
清晰简洁的描述你期往发生的事情。

### 截图/报错内容
网易云无法连接网络

### 设备信息
如果你出现问题的是**服务器**，那么请提供相关详细信息，包括但不限于：
 - 服务器的服务商：百度云，域名阿里云
 - 系统名称即具体版本：Cenos 7
 - 系统位数（如：x86_x64、i386 等）

**Comment by XIU2** [comment]
emmmm 你的意思是同一个服务器上面搭建的项目，PC上正常，IOS上不正常？
根据排除法，这说明了服务器是没问题的，问题应该是在 IOS 上面，但我没有 IOS 设备，所以也不清楚具体情况。

你可能需要去 [UnblockNeteaseMusic](https://github.com/nondanee/UnblockNeteaseMusic) 项目问问。
