### ISSUE TITLE
安装链接被拒绝访问&脚本无法启用

### ISSUE THREAD

**Issue by ec-to** [XIU2/Shell#15]
阿里弹性云计算服务器
CentOS 7.3  内核 3.10.0-514.26.2.el7.x86_64

遇到两个问题😭

1️⃣安装链接提示被拒绝访问
![2323](https://user-images.githubusercontent.com/24844835/71767927-85617c80-2f4c-11ea-8329-474439132f63.png)

已经把sh传到自己服务器上绕过了，安装没有报错，完成后遇到第二个问题
![QQ截图20200105003926](https://user-images.githubusercontent.com/24844835/71768717-de80de80-2f53-11ea-9adc-3d22b12b75f0.png)

2️⃣脚本无法启用，不管怎么启动，脚本都无法启动。查看日志提示“日志文件不存在”
已经卸载，重新安装了十几遍了，端口也换了好多个了，不知道是不是第一个问题引起的。
![QQ截图20200105003714](https://user-images.githubusercontent.com/24844835/71768694-8ea21780-2f53-11ea-999f-915d8fd32bea.png)

**Comment by ec-to** [comment]
在gcp(linux9)上没有安装成功，在网易云音乐上，提示加载失败。。

**Comment by XIU2** [comment]
国内服务器屏蔽、限速、干扰 Github 是常态。
除了下载脚本到服务器上以外，脚本安装的时候还需要下载服务脚本到服务器上面，用于启动、停止、重启、开机自启等行为。
服务脚本位置：`/etc/init.d/unblock163`
****
目前网易云音乐各平台均以在几个月前更新，不支持 HTTPS 降级 HTTP 了，所以现在使用 UnblockNeteaseMusic 项目，需要自签 SSL 证书，或者用自己的域名来转发代理。
> 参考：[#issues/65](https://github.com/nondanee/UnblockNeteaseMusic/issues/65)
