### ISSUE TITLE
播放周杰伦的歌曲时候显示加载失败

### ISSUE THREAD

**Issue by qhy5697062** [XIU2/Shell#16]
播放周杰伦的歌曲时候显示加载失败
使用的谷歌云服务器安装的脚本

**Comment by qhy5697062** [comment]
国内检测结果：
ICMP可用；TCP可用

国外检测结果：
ICMP可用；TCP可用

**Comment by qhy5697062** [comment]
感觉好像是自签证书的问题，我用的宝塔面板的NGINX签的证书，加了一段
         location / {
                proxy_http_version 1.1;
                proxy_set_header Host $http_host;
                proxy_pass http://0.0.0.0:10000;}
还是不行

**Comment by bjcxk** [comment]
你好 我遇到的问题也是 周杰伦的无法下载播放
