### ISSUE TITLE
应该可以判断一下是否已经有nodejs吧

### ISSUE THREAD

**Issue by Zxilly** [XIU2/Shell#17]
我已经有Node.js了脚本差点又给我装了一个。。。

**Comment by XIU2** [comment]
为了避免 Node 依赖路径、版本号等各种因素的影响，我采用的是 **绿色化安装** ，除了必须的服务脚本文件以外(用于控制程序开机启动、启动/停止操作)，所有文件均存放于： `/usr/local/UnblockNeteaseMusic` ，不会影响其他程序（包括安装在其他目录的 Node）。

我想大家的服务器应该不至于 几十MB 的空间都没有~

****

而且这样操作可以减少代码量和BUG几率，降低使用者出错的风险，我认为是除了 Docker 以外最佳的部署方式了。（为了安装该程序再去特地部署一个 Docker 划不来，当然如果已经有了 Docker ，那么用其部署是最佳方案）

****

如果没有疑问的话，请关闭该问题~
