### ISSUE TITLE
[BUG/unblock163.sh] -第一次安装出现错误

### ISSUE THREAD

**Issue by KANGNAMEMEDA** [XIU2/Shell#18]
### 脚本名称
unblock163.sh

### BUG描述
第一次安装出现错误

### 截图/报错内容

[信息] 开始安装/配置 依赖...
unblock163.sh: line 98: xz: command not found
unblock163.sh: line 113: xz: command not found
[错误] 解压缩依赖 xz 安装失败，请检查！

### 设备信息
如果你出现问题的是**服务器**，那么请提供相关详细信息，包括但不限于：
 - 阿里云/
 - Centos 6.9
 -x64、

）

**Comment by KANGNAMEMEDA** [comment]
![20200207103653](https://user-images.githubusercontent.com/47210006/73996290-36b56100-4996-11ea-9a70-b461fa5e9ae3.png)

**Comment by XIU2** [comment]
脚本安装 xz 依赖出错，尝试手动安装：
``` shell
yum install xz -y
```
然后贴出输出信息以便我检查出错原因。

**Comment by KANGNAMEMEDA** [comment]
可以了
[信息] 开始安装/配置 依赖...
cp: `/usr/share/zoneinfo/Asia/Shanghai' and `/etc/localtime' are the same file
[信息] 开始下载/安装...
[信息] 检测到 Node 最新版本为 [ 12.15.0 ]
[信息] 开始安装 UnblockNeteaseMusic ...
Initialized empty Git repository in /usr/local/UnblockNeteaseMusic/.git/
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 1753 (delta 0), reused 1 (delta 0), pack-reused 1750
Receiving objects: 100% (1753/1753), 1.68 MiB | 13 KiB/s, done.
Resolving deltas: 100% (1129/1129), done.
[信息] UnblockNeteaseMusic 安装完成，开始安装其依赖 Node ...
--2020-02-08 10:00:57--  https://nodejs.org/dist/v12.15.0/node-v12.15.0-linux-x64.tar.xz
Resolving nodejs.org... 104.20.22.46, 104.20.23.46, 2606:4700:10::6814:162e, ...
Connecting to nodejs.org|104.20.22.46|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14455104 (14M) [application/x-xz]
Saving to: “node-v12.15.0-linux-x64.tar.xz”

100%[====================================================================================================================================================>] 14,455,104  1.11M/s   in 22s     

2020-02-08 10:01:21 (641 KB/s) - “node-v12.15.0-linux-x64.tar.xz” saved [14455104/14455104]

chmod: cannot access `{FILE_NODE}': No such file or directory
[信息] 开始下载/安装 服务脚本(init)...
--2020-02-08 10:01:22--  https://raw.githubusercontent.com/XIU2/SHELL/master/service/unblock163_centos
Resolving raw.githubusercontent.com... 151.101.228.133
Connecting to raw.githubusercontent.com|151.101.228.133|:443... failed: Connection refused.
error reading information on service unblock163: Invalid argument
error reading information on service unblock163: Invalid argument
[信息] UnblockNeteaseMusic 服务管理脚本下载完成 !
[信息] 开始写入 配置文件...
[信息] 开始设置 iptables防火墙...
iptables: Nothing to save.                                 [WARNING]
ip6tables: Nothing to save.                                [WARNING]
[信息] 开始添加 iptables防火墙规则...
ip6tables v1.4.7: can't initialize ip6tables table `filter': Address family not supported by protocol
Perhaps ip6tables or your kernel needs to be upgraded.
ip6tables v1.4.7: can't initialize ip6tables table `filter': Address family not supported by protocol
Perhaps ip6tables or your kernel needs to be upgraded.
[信息] 开始保存 iptables防火墙规则...
iptables: Saving firewall rules to /etc/sysconfig/iptables:[  OK  ]
ip6tables: Nothing to save.                                [WARNING]
[信息] 所有步骤 安装完毕，开始启动...
