### ISSUE TITLE
HTTP代理问题

### ISSUE THREAD

**Issue by Anemone0** [XIU2/Shell#2]
关闭严格模式也无法使用HTTP代理吗？
怎么才能用应用内http代理？

**Comment by XIU2** [comment]
请按照我提供的 反馈BUG格式 提问，否则什么信息都没有，我怎么回答？猜吗？

**Comment by XIU2** [comment]
我测试无论开启还是关闭严格模式，都能在 Windows 客户端中使用HTTP代理。

**Comment by Anemone0** [comment]
那应该是我的问题，我现在也好了
多谢

还问一下啊，可以像docker那样开几个不同的端口吗？

**Comment by XIU2** [comment]
应该只要多开几个程序就行了，不过目前脚本还不支持，毕竟手动执行比写成脚本简单多了，脚本方方面面都要顾及到。

**Comment by Anemone0** [comment]
了解
多谢了
