### ISSUE TITLE
PAC模式下手机端无法访问用户相关页面

### ISSUE THREAD

**Issue by Mmahaha** [XIU2/Shell#20]
- 在其他功能正常使用的情况下，无法访问用户相关页面。
- Android客户端端采用的是代理自动配置，即http://{ip}:{port}/proxy.pac
- 服务器使用阿里云，并使用严格模式
> ![04BA956D221298DC3887AFADADEA1D17](https://user-images.githubusercontent.com/42790539/76311184-53351800-630b-11ea-8b49-bb4d4d66f50c.jpg)
> ![IMG_20200310_201105](https://user-images.githubusercontent.com/42790539/76311196-592af900-630b-11ea-9c87-2b1061d4d9b1.jpg)

**Comment by XIU2** [comment]
emmmm 本项目只回答 一键脚本使用 相关的问题，对于程序自身的问题，请前往程序项目询问作者：
https://github.com/nondanee/UnblockNeteaseMusic
