### ISSUE TITLE
[BUG/xxx.sh] - 安卓依旧有部分歌曲是灰色

### ISSUE THREAD

**Issue by a251231** [XIU2/Shell#21]
### 脚本名
unblock163.sh

### BUG描述
安卓依旧有部分歌曲是灰色
音乐有的对不上怎么解决，大佬
### 重现步骤
BUG重现完整步骤:
1. 运行...
2. 输入...
3. ...
4. 显示错误

### 预期行为
清晰简洁的描述你期往发生的事情。

### 截图/报错内容
如果有报错内容，请贴出截图或报错内容。

### 设备信息
如果你出现问题的是**服务器**，那么请提供相关详细信息，包括但不限于：
 - 服务器的服务商（如：阿里云/微软云 等）
 - 系统名称即具体版本（如：Cenos 7、Debian 9.4、Ubuntu18.04 等）
 - 系统位数（如：x86_x64、i386 等）

如果你出现问题的是**本地设备**，那么请提供相关详细信息，包括但不限于：
 - 系统类型（如：Windows、Android、IOS 等）
 - 系统位数（如：32位、64位）

**Comment by XIU2** [comment]
emmmm 这里只解决脚本安装和使用方面的问题，对于 主程序 自身的使用问题，建议前往主程序项目询问：https://github.com/nondanee/UnblockNeteaseMusic

**Comment by a251231** [comment]
收到
&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"XIU2"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月22日(星期天) 晚上7:20
收件人:&nbsp;"XIU2/SHELL"<SHELL@noreply.github.com&gt;;
抄送:&nbsp;"1029032221"<1029032221@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [XIU2/SHELL] [BUG/xxx.sh] - 安卓依旧有部分歌曲是灰色 (#21)





 
emmmm 这里只解决脚本安装和使用方面的问题，对于 主程序 自身的使用问题，建议前往主程序项目询问：https://github.com/nondanee/UnblockNeteaseMusic
