### ISSUE TITLE
有计划支持树莓派么~

### ISSUE THREAD

**Issue by poloniumn** [XIU2/Shell#24]
RT，树莓派官方系统运行后提示不支持当前系统，想通过树莓派上的AdGuard配合使用~

感谢制作一键脚本~~

**Comment by XIU2** [comment]
因为我没有树莓派，所以我没办法去支持树莓派。。。

**Comment by OpenWaygate** [comment]
树莓派 3B+
```
>>> ./unblock163.sh
[错误] UnblockNeteaseMusic 的依赖 Node 不支持当前系统位数 armv7l !
```

**Comment by OpenWaygate** [comment]
按此教程安装 node: https://zhuanlan.zhihu.com/p/127757097

注释掉这一行
https://github.com/XIU2/Shell/blob/51e536ded4d416d4b6acdfa017162b7e6b7e4732/unblock163.sh#L519

安装完成后
```
rm /usr/local/UnblockNeteaseMusic/bin/node
sudo ln -s /usr/local/node/bin/node /usr/local/UnblockNeteaseMusic/bin/node
```

再启动就行了

**Comment by OpenWaygate** [comment]
能运行成功, 但是用不了

**Comment by XIU2** [comment]
@OpenWaygate 

运行不了要看日志，看看是不是有什么报错内容。

不过我只能解决常见的报错内容（比如端口被占用什么的），其他的你可能要去 UnblockNeteaseMusic 项目问作者。

毕竟我这里只是一个 UnblockNeteaseMusic 的一键安装脚本罢了。。。
