### ISSUE TITLE
日志中一直有个报错

### ISSUE THREAD

**Issue by GodRuiAn** [XIU2/Shell#27]
大佬，我在自己家虚拟机的CentOS8上用您的这个脚本搭了解锁，查看日志的时候老出现以下提示：

[注意] 检测IP归属地(IP源：ipip.net)，如果IP较多，可能时间会比较长...
端口: 8862	 链接IP总数: 1	 当前链接IP: 
unblock163.sh:行86: ((: IP_ADDRESS_INTEGER = : 语法错误: 需要操作数 (错误符号是 "= ")

但是大部分时间好像不是很影响用。什么原因呢？

**Comment by XIU2** [comment]
v1.0.8 已更新。
 - **1. 修复** 查看链接信息时，[显示 IP+IP归属地 格式]选项报错的问题。
