### ISSUE TITLE
[BUG/unblock163.sh] - iOS客户端无法解锁网易云，已参照#14

### ISSUE THREAD

**Issue by Hbxuan** [XIU2/Shell#29]
### 脚本名称
unblock163.sh

### BUG描述
您的脚本非常好用。我安装以后成功在windows客户端解锁网易云。
但之后按照#14 的方法进行了配置，依然无法在iOS客户端解锁网易云。

### 截图/报错内容
比如说已经下架的歌曲Monster，可以显示为黑色，但播放时显示：
![image](https://user-images.githubusercontent.com/29568196/87713466-d1835880-c7dc-11ea-887a-9cff5a88f4c6.png)

查看服务器日志内容如下：
[28481189] Monsters
http://ws.stream.qqmusic.qq.com/M5000015qkUp0ExUoV.mp3?guid=7332953645&vkey=A958FF4556D6AF76BE2C4C92AC4E6B3A316D5FC5C29E4657AFF843B395252079E332DC578DBF69D939C98864D14802B94FA19B12768FFCF3&uin=0&fromtag=66
![image](https://user-images.githubusercontent.com/29568196/87715540-165cbe80-c7e0-11ea-8b16-1b99c4784af4.png)

### 设备信息
 - 腾讯云服务器
 - Debian 9.0

**本地设备**：
 - iOS 13
 - 代理软件quantumult X

使用时人在境外，服务器在国内，不知是否有影响？

非常感谢您的工作。

**Comment by Hbxuan** [comment]
iOS端下载了并安装了ca证书：https://raw.githubusercontent.com/nondanee/UnblockNeteaseMusic/master/ca.crt
在设置 > 通用 > 关于本机 > 证书信任设置里手动信任了证书

**Comment by XIU2** [comment]
因为我没有 IOS 设备，所以无法测试，不过我去[UnblockNeteaseMusic #64](https://github.com/nondanee/UnblockNeteaseMusic/issues/65)看了下，看到了这句话：
> 如果你使用 https endpoint 转发音源，请检查你的启动参数是否正确（不要指定第二个端口号）  

这里可能指的是要用单个端口，也就是脚本设置端口时不使用 XXXX:XXXX 方式的端口，而只是写一个端口。
你可以试试。

**Comment by Hbxuan** [comment]
Thanks!!!
折腾半天，已经成功，iOS也可以听啦，但wifi下用pac似乎还是不行。虽然自己完全不知道为什么会成功。不过成功就好。
非常感谢大佬！！

**Comment by OpenWaygate** [comment]
大佬，我之前用的[这篇教程](https://merlinblog.xyz/wiki/neteasemusic.html)在Ubuntu上部署的
主要命令是`/usr/bin/node app.js -p 10086:10087 -e https://music.163.com`
这个我在IOS的Quantumult X里可以用

我换用一键脚本后无论是指定两个（10086:10087）还是一个端口（10086）都无法连接，
这个选项`-e https://music.163.com`要怎么弄啊?

**Comment by XIU2** [comment]
@OpenWaygate 

默认服务脚本里写的是 http:// 的，你需要修改一下
``` bash
# 编辑/打开服务脚本
nano /etc/init.d/unblock163

# 找到下面这条命令（大概四五十行）
# 将 http:// 改成 https://
nohup "${FILE_NODE}" "${FILE}" -a 0.0.0.0 -p ${PORT} -o ${SOURCE} -s -e "http://music.163.com" > "${FILE_LOG}" 2>&1 &

# 然后按下 Ctrl+X 退出，提示你保存，按下 Y 键，再按两次回车就行了
# 然后重启服务试试
```

**Comment by OpenWaygate** [comment]
弄了半天终于成功了，原来得禁用严格模式。
禁用严格模式后，在网易云音乐HD版能用，但网易云音乐显示网络不给力，所以我又在非严格模式那一行加上了`-e https://music.163.com`,发现可以用了
多谢大佬！
