### ISSUE TITLE
[BUG] - v1.0.1版本 service/unblock163_centos文件在53多了一个}导致启动失败

### ISSUE THREAD

**Issue by shawndodo** [XIU2/Shell#3]
### BUG描述
项目版本: v1.0.1 service/unblock163_centos文件在53多了一个}导致启动失败
第一次安装、启动时到启动这一步提示启动失败
报错信息是unblockneteasemusic: error: extra arguments found: } 具体可看下面截图
在看了本地/etc/init.d/unblock163文件的代码后确认是53行在"http://music.163.com"后面多了一个}
在修改后即可成功启动

### 重现步骤
BUG重现完整步骤:
1. 运行...
![image](https://user-images.githubusercontent.com/16178252/64163016-03185d00-ce73-11e9-8c34-f79eed686c24.png)

2. 输入...
端口输入的是8000 其他都是默认
3. ...
4. 显示错误
![image](https://user-images.githubusercontent.com/16178252/64162958-e54af800-ce72-11e9-84d8-c25ee6e2909a.png)
![image](https://user-images.githubusercontent.com/16178252/64162975-ef6cf680-ce72-11e9-8664-f9174db5dffa.png)

### 设备信息
如果你出现问题的是**服务器**，那么请提供相关详细信息，包括但不限于：
 - 服务器的服务商 vultr
 - 系统名称即具体版本 centos7
 - 系统位数 x86_x64

**Comment by XIU2** [comment]
已修复，请更新脚本（等待Github更新缓存）。
中午的时候空闲时间更新没来得及测试就上传了，我的锅...
