### ISSUE TITLE
[BUG/Unblock163.sh] - 网易云win客户端是否开启代理？

### ISSUE THREAD

**Issue by 0xDayDream** [XIU2/Shell#31]
### 脚本名称
Unblock163.sh

### BUG描述
在Digital Ocean的Ubuntu里脚本部署成功，之前部署aria2时端口80分配过了，给脚本设置的83端口，日志里显示正常，hosts修改完毕后，打开网易云会提示无网络连接，重开几次后设置里开启代理输入了服务器的和端口，这样做可以搜到歌曲，但是搜索、听歌下载速度非常慢，kb/s~b/s都有，不知道是不是操作错误？

网易云2.02版本

**Comment by XIU2** [comment]
1. 你设置非 80 端口，那么自然就不能使用 Hosts 方式了，因为网易云音乐客户端默认是使用 80（或443）端口去访问的。
2. 非 80 端口只能去网易云音乐客户端里设置代理。
3. 能用，但是速度慢，那可能跟你的服务器的网络质量有关（比如你与该服务器之间连接质量差）。
毕竟如果是配置问题的话，应该是完全不能用的。

**Comment by 0xDayDream** [comment]
了解了，今天和服务器连接的速度确实很感人，ssh软件上接受指令结果都很慢，万分感谢
