### ISSUE TITLE
安装完成后没有出现配置信息

### ISSUE THREAD

**Issue by zxin2001** [XIU2/Shell#32]
阿里云，查询到配置，但是选择[4]之后没反应，重新查看状态也是已安装未启动。请问这是什么原因？选[9]也没有看到日志文件。

**Comment by zxin2001** [comment]
`<img src='https://disk.1onx.cn/%E5%9B%BE%E7%89%87/%E8%A7%A3%E9%94%81%E7%BD%91%E6%98%93%E4%BA%91%E9%97%AE%E9%A2%981.jpg' />`

**Comment by zxin2001** [comment]
<img src='https://disk.1onx.cn/%E5%9B%BE%E7%89%87/%E8%A7%A3%E9%94%81%E7%BD%91%E6%98%93%E4%BA%91%E9%97%AE%E9%A2%981.jpg' />

**Comment by x2101** [comment]
<img src='https://disk.1onx.cn/%E5%9B%BE%E7%89%87/%E5%90%AF%E5%8A%A8%E6%B2%A1%E5%8F%8D%E5%BA%94%E9%97%AE%E9%A2%982.jpg' />

**Comment by x2101** [comment]
https://disk.1onx.cn/%E5%9B%BE%E7%89%87/%E5%90%AF%E5%8A%A8%E6%B2%A1%E5%8F%8D%E5%BA%94%E9%97%AE%E9%A2%982.jpg

**Comment by x2101** [comment]
我已经解决了，谢谢啦
