### ISSUE TITLE
电脑可以使用，怎么转换成QX节点？

### ISSUE THREAD

**Issue by Gollum916** [XIU2/Shell#33]
电脑可以使用，怎么转换成QX节点？

**Comment by XIU2** [comment]
QX 是什么？
解锁网易云音乐的那个脚本创建的是 HTTP 代理，其他软件只要支持 HTTP 代理就能用。

**Comment by Gollum916** [comment]
QuantumultX代理软件，这个http怎么转换成SS节点？

**Comment by Gollum916** [comment]
> QX是什么？
> 解锁网易云音乐的那个脚本创作的是HTTP代理，其他软件只要支持HTTP代理即可用。

QuantumultX代理软件，这个http怎么转换成SS路由器？

**Comment by XIU2** [comment]
HTTP 代理 无法转换为 SS 代理。
