### ISSUE TITLE
很感谢你的努力

### ISSUE THREAD

**Issue by 1965514404** [XIU2/Shell#35]
一直想找从蓝奏云上传和下载文件的方法(不想买服务器,只是做为上传下载数据使用),找到的大部分是python,代码看不懂,也没办法直接使用,感谢提供的shell,虽然没有root不能直接使用,但让我较为直观的看懂了上传的方法,虽然很麻烦我现在还没有成功,但是我会努力的,

**Comment by 1965514404** [comment]
想问一下之后还会更新下载的方法么

**Comment by XIU2** [comment]
你指的是下载自己网盘内的文件还是下载指定分享连接的文件？

**Comment by 1965514404** [comment]
下载一个文件夹下的所有txt文件

**Comment by XIU2** [comment]
参考了下隔壁的 [Python 版代码](https://github.com/zaxtyson/LanZouCloud-API/blob/master/lanzou/api/core.py#L434) ，发现这下载比上传麻烦多。  
最主要的是，下载时可能会遇到验证码（特别是连续下载时），这图片验证码放到 Linux 上就很麻烦了。。。

**Comment by 1965514404** [comment]
那python是如何处理的,对接了ocr识图么?那个php和python看不懂,也不知道如何去调用.....能不能截取到验证码的base64码,这样能渲染出图片,去手动识别了

**Comment by XIU2** [comment]
看了下，似乎是把网页内的部分信息直接 POST 提交后就验证通过了。这是什么狗屁验证码，这么容易跳过...

**Comment by 1965514404** [comment]
感觉怪怪的，那验证码有什么方法规避么？

**Comment by XIU2** [comment]
自从前段时间蓝奏云把 Cookie 改成 3 天有效期后，就很烦了。  
这意味着要使用脚本，就需要每 3 天换一次新 Cookie（你需要手动登录后才能获得）。  

所以已经没什么意义了。。。
