### ISSUE TITLE
按照脚本流程来，可以正常启动，但是IOS端设置好小火箭后没有网络

### ISSUE THREAD

**Issue by GeorgeJu95** [XIU2/Shell#36]
可以运行，IOS客户端设置好小火箭，服务器ip，+自己设置的端口。然后网易云客户端就没有网络了

**Comment by XIU2** [comment]
我记得 IOS 还需要折腾证书什么的吧？

**Comment by GeorgeJu95** [comment]
> 我记得 IOS 还需要折腾证书什么的吧？

弄了证书，显示网络不给力/无版权。不过安卓和电脑我试了试，脚本运行下来，如果设置4000:4002这种端口就不行，默认的80可以运行 = =

**Comment by XIU2** [comment]
我没有 IOS 设备，所以也不太清楚，你只能去 [UnblockNeteaseMusic](https://github.com/nondanee/UnblockNeteaseMusic) 问下作者了。

至于电脑上，如果你用的是 Hosts 方式（域名指向服务器IP），那么你只能使用 80 端口，如果你是在 网易云音乐PC客户端 上设置代理的话，才能使用其他端口。

**Comment by GeorgeJu95** [comment]
好的。谢谢你!



---原始邮件---
发件人: "XIU2"<notifications@github.com&gt;
发送时间: 2020年9月17日(周四) 中午12:29
收件人: "XIU2/Shell"<Shell@noreply.github.com&gt;;
抄送: "GeorgeJu95"<980998863@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [XIU2/Shell] 按照脚本流程来，可以正常启动，但是IOS端设置好小火箭后没有网络 (#36)




 
我没有 IOS 设备，所以也不太清楚，你只能去 UnblockNeteaseMusic 问下作者了。
 
至于电脑上，如果你用的是 Hosts 方式（域名指向服务器IP），那么你只能使用 80 端口，如果你是在 网易云音乐PC客户端 上设置代理的话，才能使用其他端口。
