### ISSUE TITLE
能否使用本地unblocknetease

### ISSUE THREAD

**Issue by tnxl** [XIU2/Shell#37]
因为国内的腾讯云服务器clone和下载非常慢,可否添加设置,以使用本地已经下好的unblocknetease脚本和本地nodejs

**Comment by XIU2** [comment]
这样吧。
- 首先，手动新建文件夹：  
``` bash
mkdir /usr/local/UnblockNeteaseMusic
mkdir /usr/local/UnblockNeteaseMusic/node
```
- 然后，把脚本 [297 行](https://github.com/XIU2/Shell/blob/master/unblock163.sh#L297)的 `_DOWNLOAD` 前面加上井号注释掉。
- 接着，运行脚本安装，安装完自动启动会报错（因为没有 node 和 主程序 文件）。
- 随后，你再把 node 和 主程序 文件放到指定文件夹内。
```
目录结构必须是：
主程序：/usr/local/UnblockNeteaseMusic/app.js
node：/usr/local/UnblockNeteaseMusic/node/bin/node"
```
- 最后，运行看看。

**Comment by XIU2** [comment]
### 2021年03月25日，版本 v1.1.1
 - **1. 调整** UnblockNeteaseMusic 仓库源为国内镜像源。  
> 有效解决国内服务器从 Github 下载慢/无法下载的问题。

至于 NodeJS 在国内下载好像并不是很慢。
