### ISSUE TITLE
动态代理proxy.pac无法访问

### ISSUE THREAD

**Issue by 704787189** [XIU2/Shell#38]
大佬为什么开启脚本后 动态代理proxy.pac无法访问
还有可以自己设置网易云的ip吗

**Comment by XIU2** [comment]
客户端内直接设置 HTTP 代理是否可用？
【自己设置网易云的ip】具体指的是哪里？

**Comment by 704787189** [comment]
客户端内 HTTP 代理可以用
UnblockNeteaseMusic脚本有个 -f 可以指定网易云的ip指令

**Comment by XIU2** [comment]
HTTP 代理可以用，说明程序没问题。  
pac 无法使用可能是 pac 文件规则有问题，这你就要去 [UnblockNeteaseMusic](https://github.com/nondanee/UnblockNeteaseMusic) 项目问了。

目前脚本还没有加上 `-f`，你可以临时编辑一下系统服务脚本，加上 `-f` 参数：
```
nano /etc/init.d/unblock163

# 在大概 四五十行，找到（前者是普通模式，后者是严格模式）：
nohup "${FILE_NODE}" "${FILE}" -a 0.0.0.0 -p ${PORT} -o ${SOURCE} > "${FILE_LOG}" 2>&1 &
else
nohup "${FILE_NODE}" "${FILE}" -a 0.0.0.0 -p ${PORT} -o ${SOURCE} -s -e "http://music.163.com" > "${FILE_LOG}" 2>&1 &

# 你可以在 > 前面追加一个 -f x.x.x.x 的参数，示例如下：

nohup "${FILE_NODE}" "${FILE}" -a 0.0.0.0 -p ${PORT} -o ${SOURCE} -f x.x.x.x > "${FILE_LOG}" 2>&1 &
else
nohup "${FILE_NODE}" "${FILE}" -a 0.0.0.0 -p ${PORT} -o ${SOURCE} -s -e "http://music.163.com" -f x.x.x.x > "${FILE_LOG}" 2>&1 &

# 然后按下 Ctrl+X 退出，然后按两下回车确认保存，最后重启程序试试。
```

如果你试了没问题，可以告诉我，然后我更新脚本加上该功能（主要是我已经很长时间没用过这程序了，所以需要你来测试）。

**Comment by 704787189** [comment]
改了脚本可以重启，但不知道改成功了没

**Comment by XIU2** [comment]
@704787189 
可以正常启动，也可以正常使用（网易云音乐客户端），就说明成功了。

**Comment by 704787189** [comment]
网易云可以用，谢谢大佬

**Comment by XIU2** [comment]
等我几分钟更新脚本，一会你帮我测试一下吧。

**Comment by 704787189** [comment]
改好了说一声，我帮你测试一下

**Comment by XIU2** [comment]
我更新脚本了，你去试试吧，我只进行了简单的测试（确保不会出现格式错误等低级错误）

#### 2020年12月01日，版本 v1.1.0 :id=110
 - **1. 新增** 指定网易云音乐 IP（即 -f 参数）。

**Comment by 704787189** [comment]
可以了，大佬厉害

**Comment by XIU2** [comment]
那我就关闭该 Issues 了。
如果觉得好用，**走之前点个 ⭐ 吧！**
