### ISSUE TITLE
IOS按教程设置好后播放歌曲提示网络不给力

### ISSUE THREAD

**Issue by Accenemy** [XIU2/Shell#39]

**Comment by XIU2** [comment]
[UnblockNeteaseMusic](https://github.com/nondanee/UnblockNeteaseMusic#使用) 项目说明里写了：
**iOS 客户端 (配置 https endpoint 或使用自签证书)**

所以脚本安装完后，在 IOS 设备上并不能直接使用。

- 配置 https endpoint 可以参考 #14 #29 
- 自签证书请参考 [UnblockNeteaseMusic #48](https://github.com/nondanee/UnblockNeteaseMusic/issues/48)
