### ISSUE TITLE
[BUG] - 在ios网易云端无法播放

### ISSUE THREAD

**Issue by jinoogui** [XIU2/Shell#4]
### BUG描述
在ios网易云端上播放提示网络连接错误无法播放下载

### 重现步骤
BUG重现完整步骤:
在ios手机wifi处设置代理为http://106.13.168.133:8083/proxy.pac
服务端运行正常 windows端可用 ios端报网络连接错误

### 预期行为
无法播放

### 设备信息
如果你出现问题的是**服务器**，那么请提供相关详细信息，包括但不限于：
百度云服务器 
 CentOS / 6.5 x86_64 (64bit)
服务器在华东 - 苏州

**Comment by XIU2** [comment]
这并不是我脚本的问题，是主程序的问题。
参考这个：https://github.com/nondanee/UnblockNeteaseMusic/issues/137

**Comment by panchao0716** [comment]
@jinoogui 请问解决了吗

**Comment by jinoogui** [comment]
没有=-=  换老版本网易云无效
