### ISSUE TITLE
[BUG/lanzou_up.sh] - 脚本失效

### ISSUE THREAD

**Issue by Celeter** [XIU2/Shell#40]
### 脚本名称
lanzou_up.sh

### 问题描述
显示文件上传成功，进入蓝奏云中并没有该文件

**Comment by XIU2** [comment]
我试了下，目前是可以正常上传的。

**Comment by Celeter** [comment]
![Screenshot_20210227-163421](https://user-images.githubusercontent.com/48249130/109382169-c0292f80-7919-11eb-911c-075aa6471169.jpg)

**Comment by XIU2** [comment]
蓝奏云不支持 txt 文件后缀。

**Comment by Celeter** [comment]
![Screenshot_20210227-163703](https://user-images.githubusercontent.com/48249130/109382212-14341400-791a-11eb-95ba-ebc297cc4b50.jpg)

**Comment by XIU2** [comment]
你用网页上传一下 txt 后缀的文件就明白了。

跟我说这个没用，脚本调用的是网页接口。

**Comment by Celeter** [comment]
我手动上传txt成功了

**Comment by Celeter** [comment]
好吧

**Comment by XIU2** [comment]
网页端上传 txt 文件会提示：未开放此格式的文件

**Comment by Celeter** [comment]
好的，谢谢解答
