### ISSUE TITLE
解决腾讯云｜阿里云 git clone失败的情况

### ISSUE THREAD

**Issue by Jratil** [XIU2/Shell#41]
在作者说的297行的 DOWNLOAD 这里，把 git clone 里面的 github 链接换成 gitee 的。  
https://gitee.com/mirrors/UnblockNeteaseMusic.git  
换成这个，这个是 UnblockNeteaseMusic 在 gitee 每天定时同步，希望作者也能把 git 仓库换一下    
![image](https://user-images.githubusercontent.com/29191680/112459416-c5eb2700-8d98-11eb-8564-9de6a70de020.png)

**Comment by XIU2** [comment]
OK，已更新。

### 2021年03月25日，版本 v1.1.1
 - **1. 调整** UnblockNeteaseMusic 仓库源为国内镜像源。  
> 有效解决国内服务器从 Github 下载慢/无法下载的问题。

**Comment by GenghisYoung233** [comment]
使用国内镜像的话似乎会产生国外服务器（谷歌云）无法下载的问题。

1.VPS：谷歌云（Google Cloud Platform），端口已全部开放
```bash
  [信息] 开始下载/安装...
  [信息] 检测到 Node 最新版本为 [ 14.16.1 ]
  [信息] 开始安装 UnblockNeteaseMusic ...
  Cloning into '/usr/local/UnblockNeteaseMusic'...
  fatal: unable to access 'https://gitee.com/mirrors/UnblockNeteaseMusic.git/': Failed to connect to gitee.com port 443
  : Connection timed out
  [错误] UnblockNeteaseMusic 下载失败 !
```

2.AWS lightsail没有问题。
```bash
  [信息] 开始下载/安装...
  [信息] 检测到 Node 最新版本为 [ 14.16.1 ]
  [信息] 开始安装 UnblockNeteaseMusic ...
  Cloning into '/usr/local/UnblockNeteaseMusic'...
  remote: Enumerating objects: 2031, done.
  remote: Counting objects: 100% (2031/2031), done.
  remote: Compressing objects: 100% (1385/1385), done.
  remote: Total 2031 (delta 1319), reused 945 (delta 634), pack-reused 0
  Receiving objects: 100% (2031/2031), 1.67 MiB | 1.24 MiB/s, done.
```

**Comment by Jratil** [comment]
> 使用国内镜像的话似乎会产生国外服务器（谷歌云）无法下载的问题。
> 
> 1.VPS：谷歌云（Google Cloud Platform），端口已全部开放
> 
> ```shell
>   [信息] 开始下载/安装...
>   [信息] 检测到 Node 最新版本为 [ 14.16.1 ]
>   [信息] 开始安装 UnblockNeteaseMusic ...
>   Cloning into '/usr/local/UnblockNeteaseMusic'...
>   fatal: unable to access 'https://gitee.com/mirrors/UnblockNeteaseMusic.git/': Failed to connect to gitee.com port 443
>   : Connection timed out
>   [错误] UnblockNeteaseMusic 下载失败 !
> ```
> 
> 2.AWS lightsail没有问题。
> 
> ```shell
>   [信息] 开始下载/安装...
>   [信息] 检测到 Node 最新版本为 [ 14.16.1 ]
>   [信息] 开始安装 UnblockNeteaseMusic ...
>   Cloning into '/usr/local/UnblockNeteaseMusic'...
>   remote: Enumerating objects: 2031, done.
>   remote: Counting objects: 100% (2031/2031), done.
>   remote: Compressing objects: 100% (1385/1385), done.
>   remote: Total 2031 (delta 1319), reused 945 (delta 634), pack-reused 0
>   Receiving objects: 100% (2031/2031), 1.67 MiB | 1.24 MiB/s, done.
> ```

看看叫作者能不能弄两个版本，或者加选项判断使用gitee 或者 github
