### ISSUE TITLE
[BUG/unblock163.sh] 连接效率很低

### ISSUE THREAD

**Issue by huanx9** [XIU2/Shell#42]
用的是国内的  为什么加载这么慢  有时候甚至加载失败

但是有时候可以解锁 说明脚本没问题 不知道效率这么低 问题出在哪里。

**Comment by XIU2** [comment]
这个你去问 [UnblockNeteaseMusic](https://github.com/nondanee/UnblockNeteaseMusic) 更合适。。。
而我已经很久没用过这个程序了，无法回答你这个问题。
