### ISSUE TITLE
 支持arm64 cpu

### ISSUE THREAD

**Issue by qy2009** [XIU2/Shell#44]
能增加去arm64 cpu的支持嘛？ 我运行后提示：
[错误] UnblockNeteaseMusic 的依赖 Node 不支持当前系统位数 aarch64 !

谢谢啦

**Comment by XIU2** [comment]
不是很清楚你这个是 ARMv7 还是 ARMv8。
NodeJS 这个依赖的 ARM 分为两个。

**Comment by qy2009** [comment]
ARMv8

谢谢啦

**Comment by XIU2** [comment]
我更新脚本了，你试试吧，不过因为我没有 ARM 架构的服务器，所以没有做测试。
早上时间有限，有问题了下午我再处理。

**Comment by qy2009** [comment]
还是不行，同样的显示

Last-modified header missing -- time-stamps turned off.
2021-07-25 23:44:18 (144 MB/s) - ‘unblock163.sh’ saved [22899/22899]

[错误] UnblockNeteaseMusic 的依赖 Node 不支持当前系统位数 aarch64 !


这是我的系统：
root@arm:~# cat /etc/issue
Debian GNU/Linux 10 \n \l
root@arm:~# uname -m
aarch64

**Comment by xiaoxiongzi** [comment]
`[[ "${SYSTEM_BIT}" !=  "x86_64" ]] || [[ "${SYSTEM_BIT}" !=  "aarch64" ]]` 是不是要改为`[[ "${SYSTEM_BIT}" !=  "x86_64" ]] && [[ "${SYSTEM_BIT}" !=  "aarch64" ]]`。

**Comment by xiaoxiongzi** [comment]
`[[ "${SYSTEM_BIT}" !=  "x86_64" ]] || [[ "${SYSTEM_BIT}" !=  "aarch64" ]] ` 
是不是要改为
`[[ "${SYSTEM_BIT}" !=  "x86_64" ]] && [[ "${SYSTEM_BIT}" !=  "aarch64" ]] `

**Comment by XIU2** [comment]
@xiaoxiongzi 是的，刚才看了下早上太急写错了。
@qy2009 已经更新了，你再试试吧。

**Comment by qy2009** [comment]
已经成功啦！ 谢谢！
