### ISSUE TITLE
[BUG/lanzou_up.sh] - 小功能   VPS 中转 歌曲到蓝奏网备份

### ISSUE THREAD

**Issue by sammisssam** [XIU2/Shell#45]
### 重现步骤

NeteaseMusice 下载音乐 放在 VPS 文件夹 备份到网盘  删除VPS 文件   备份完成  

利用VPS 文件夹 定期备份音乐文件

建议 同步到 aliyun 网盘   百度网盘  蓝奏网盘

**Comment by XIU2** [comment]
这个蓝奏云上传脚本基本上是报废了，无法通过账号密码登录，而通过 Cookie 的话，有效期只有两三天，需要天天手动更换。。。
