### ISSUE TITLE
当前不支持群晖系统，求支持一下。。。

### ISSUE THREAD

**Issue by zibo1996** [XIU2/Shell#5]
### 脚本名称
xxx.sh

### BUG描述
对BUG的清晰简洁描述。

### 重现步骤
BUG重现完整步骤:
1. 运行...
2. 输入...
3. ...
4. 显示错误

### 预期行为
清晰简洁的描述你期往发生的事情。

### 截图/报错内容
如果有报错内容，请贴出截图或报错内容。

### 设备信息
如果你出现问题的是**服务器**，那么请提供相关详细信息，包括但不限于：
 - 服务器的服务商（如：阿里云/微软云 等）
 - 系统名称即具体版本（如：Cenos 7、Debian 9.4、Ubuntu18.04 等）
 - 系统位数（如：x86_x64、i386 等）

如果你出现问题的是**本地设备**，那么请提供相关详细信息，包括但不限于：
 - 系统类型（如：Windows、Android、IOS 等）
 - 系统位数（如：32位、64位）

**Comment by XIU2** [comment]
没有测试设备，我也没办法适配群晖设备。

**Comment by e4rlj** [comment]
哈哈哈，黑群晖也很香的。可以搞一个玩玩
