### ISSUE TITLE
[unblock163.sh] 安装脚本出错

### ISSUE THREAD

**Issue by shuangyueaishang** [XIU2/Shell#53]
unblock163.sh脚本执行bash unblock163.sh安装失败，无法解析ip

**Comment by XIU2** [comment]
请贴出从运行脚本开始的所有输出内容，我才能判断。  
不过注意我只解决脚本自身问题，如果是 UnblockNeteaseMusic 程序自身的问题我是无法解决的，毕竟我已经两年没用过这程序了，因此我也很长时间都没用过该脚本了。

**Comment by shuangyueaishang** [comment]
![N59CDY@N~LDFC74L` R1MCX](https://user-images.githubusercontent.com/33510807/153818176-f62c02c8-e9fd-4b8a-9959-9fec60ada9c4.png)

**Comment by XIU2** [comment]
看了下，发现这个 git 镜像失效了。。。
我去找找其他的。

**Comment by XIU2** [comment]
我更新了下脚本，换了个镜像源，你再去试试吧。

**Comment by shuangyueaishang** [comment]
可以了

**Comment by XIU2** [comment]
如果脚本没什么问题的话，记得关闭该 Issues~
