### ISSUE TITLE
使用代理后，网易云无法连接网络

### ISSUE THREAD

**Issue by shuangyueaishang** [XIU2/Shell#54]
如题
![image](https://user-images.githubusercontent.com/33510807/154181595-f776556a-e14d-48bd-968b-c6e4507bc7cc.png)

**Comment by XIU2** [comment]
我只解答脚本安装使用相关问题，对于 UnblockNeteaseMusic 等问题，请去相应项目下询问作者。
https://github.com/UnblockNeteaseMusic/server
