### ISSUE TITLE
仓库镜像源无法拉取

### ISSUE THREAD

**Issue by 704787189** [XIU2/Shell#55]
https://hub.fastgit.xyz/ 这个仓库镜像源拉一直报429
![image](https://user-images.githubusercontent.com/75265337/163671252-31168974-7c0f-4dcd-a60d-72e5f244af3c.png)

https://gitclone.com/github.com/  换成这个可以秒拉

**Comment by XIU2** [comment]
已更新~

我记得 gitclone.com 这个缓存时间比较长，以 UnblockNeteaseMusic 项目的更新频率，这意味可能 clone 下来的不是最新文件。
所以我改用的是另一个无缓存的镜像源（我找了好几个，测试对比了下，感觉这个香港的最快）：
```
git clone -b enhanced https://api.mtr.pub/UnblockNeteaseMusic/server.git
```
