### ISSUE TITLE
关于音质和ios的问题

### ISSUE THREAD

**Issue by ENOCHISUN** [XIU2/Shell#6]
能否加入高音质的选项以及ios具体怎么操作，麻烦题主能弄一下吗？

**Comment by XIU2** [comment]
音质取决于音源匹配结果。这个需要你自行调整音源排序（依次把各个音源排在首位）。
`qq`是曲库全但是只提供 128Kbps，而 `kugou  kuwo` 提供 320Kbps 但是曲库没QQ全。

至于 IOS 这个我没设备。。。
