### ISSUE TITLE
gcp连不上59.111.21.13

### ISSUE THREAD

**Issue by wanjun0214** [XIU2/Shell#7]
{ Error: connect ECONNREFUSED 59.111.21.13:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '59.111.21.13',
  port: 443 }

**Comment by xiexinxinclimb** [comment]
看下设置的端口是否被占用了~我遇到过同样的，换掉端口就行了

**Comment by xiexinxinclimb** [comment]
> { Error: connect ECONNREFUSED 59.111.21.13:443
> at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
> errno: 'ECONNREFUSED',
> code: 'ECONNREFUSED',
> syscall: 'connect',
> address: '59.111.21.13',
> port: 443 }

看下设置的端口是否被占用了~我遇到过同样的，换掉端口就行了

**Comment by XIU2** [comment]
> { Error: connect ECONNREFUSED 59.111.21.13:443
> at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
> errno: 'ECONNREFUSED',
> code: 'ECONNREFUSED',
> syscall: 'connect',
> address: '59.111.21.13',
> port: 443 }

尝试更新一下主程序。
这个问题主程序在10天前就解决了。
