### ISSUE TITLE
[错误] Node 最新版本获取失败！

### ISSUE THREAD

**Issue by eliver** [XIU2/Shell#8]
请输入数字 [0-10]:1
[信息] 开始设置 用户配置...
请输入要使用的代理端口。 [1-65535]
[注意] 如果你在本地通过 Hosts 方式使用该代理，那么只能选择 80 端口，其他方式不限制。
(默认: 80):

------------------------
        代理端口 :  80 
------------------------

请输入要使用的音源排序。 [qq kuwo kugou baidu xiami migu joox]
[注意] 音源排序指的是，无版权音乐会根据此处顺序优先匹配首位音源，如果匹配到就返回，反之就继续往后匹配。
[注意] 不同音源之间请用空格隔开。
(默认: qq migu kuwo kugou baidu):

------------------------
        音源排序 :  qq migu kuwo kugou baidu 
------------------------

是否启用严格模式？[Y/n]
[注意] 启用严格模式后，本代理仅允许网易云音乐域名访问，即本地设备只能通过 Host 或 PAC 使用，强烈建议开启，否则所有设备流量都会经过本代理。
(默认：Y [启用]):

------------------------
        严格模式 :  YES 
------------------------

[信息] 开始安装/配置 依赖...
[信息] 开始下载/安装...
**[错误] Node 最新版本获取失败！**

**Comment by XIU2** [comment]
@eliver 你在服务器上面执行这个命令看返回什么：
``` bash
wget -qO- https://nodejs.org/en/download/| grep "Latest LTS Version"| awk -F '<strong>' '{print $2}'| awk -F '</strong>' '{print $1}'
```
如果什么也没有，那么就依次从尾部删除 | 及后面的内容例如这样：
``` bash
wget -qO- https://nodejs.org/en/download/| grep "Latest LTS Version"| awk -F '<strong>' '{print $2}'

wget -qO- https://nodejs.org/en/download/| grep "Latest LTS Version"

wget -qO- https://nodejs.org/en/download/
```
直到有输出为止。
把输出内容告诉我。

**Comment by eliver** [comment]
@XIU2 尝试执行上述的所有命令都没有返回，如果你在自己的服务器上没有遇到这个问题的话，那就是我的Ubuntu 18.4 LTS有坑。。。。
![无标题](https://user-images.githubusercontent.com/9433335/66029558-1a11a400-e532-11e9-861f-4ffb23124cb0.png)

我临时把Line 69行改成了NEW_VER_NODE=10.16.3去获取最新的Node版本成功安装了，谢谢~

**Comment by XIU2** [comment]
@eliver 你尝试去掉代码里 wget 后面的 -qO- 再试试。

**Comment by XIU2** [comment]
我更新了下，v1.0.3：获取 Node 最新版本失败时，将使用备用的版本号。
