### ISSUE TITLE
[BUG/unblock163.sh] - 无法监听443端口

### ISSUE THREAD

**Issue by StringKe** [XIU2/Shell#9]
### 脚本名称
unblock163.sh

### BUG描述
无法设置 https 端口

### 重现步骤
BUG重现完整步骤:
1. 运行 unblock163.sh
2. 输入 7
3. 输入 1
4. 输入 80:443

### 预期行为
在mac下此脚本需要设置监听443端口的https流量

### 截图/报错内容
![image](https://user-images.githubusercontent.com/31089228/68520299-6e4a3980-02d1-11ea-8166-1c7e33314963.png)

[为什么需要 443 端口](https://github.com/nondanee/UnblockNeteaseMusic/issues/48#issuecomment-477870013)
![image](https://user-images.githubusercontent.com/31089228/68520309-828e3680-02d1-11ea-9ee2-4c60a5387623.png)

**Comment by XIU2** [comment]
已更新，请测试，测试无误请关闭该问题。

### 2019年11月09日，版本 v1.0.4
 - **1. 新增** 支持 HTTP:HTTPS 监听双端口，搭配自签证书使用。

****

这个BUG是因为我的脚本没有适配该参数使用方式。
我的脚本目前只支持单个端口，所以你这样填写会端口检测失败（回车后脚本会检查你写的端口号是否正确）。
添加了一个判断，当用户输入信息中包含冒号 : 时，跳过端口检测。
